name: C CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the program
      run: make

    - name: Run the program
      run: ./main
