name: C Project CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile the project
      run: make

    - name: Run the program (simulate user input)
      run: |
        echo -e "1\n101\nAlice\n2\n3" | ./student_app
