name: StudentSystem CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile
      run: make

    - name: Run the program with simulated input
      run: |
        echo -e "1\n101\nAlice\n85.5\n1\n102\nBob\n92.3\n2\n3\n4" | ./student_app
